Cookbook
darya-varabei/ios-tasks pull request #15
Opened 2021-10-25 08:28 UTC by darya-varabei

- implement data loading from url using GDC
- loading image from url using NSOparationQueue
- improving the responsiveness of the app using multithreading

2021-11-02 16:44 UTC, EugeneItechart commented on Cookbook/Cookbook/DetailViewController.swift
> +                self.image = UIImage(data: data! as Data)
crash operator is still there

2021-11-02 16:45 UTC, EugeneItechart commented on Cookbook/Cookbook/DetailViewController.swift
> +        return cell!
force unwrapping. Why do you continue using it?

2021-11-13 14:45 UTC, EugeneItechart requested changes
Please fix the comments and implement additional GCD use cases using disptach_group or dispatch_barrier

2021-11-13 14:45 UTC, EugeneItechart commented on Cookbook/Cookbook/DetailViewController.swift
> +                sleep(1)
Have you made any updates recently? We've discussed that sleep(1) is a bad practice especially on the main thread

2021-11-13 14:45 UTC, EugeneItechart commented on Cookbook/Cookbook/DetailViewController.swift
> +                self.image = UIImage(data: data! as Data)
CRASH operator is still here!

2021-11-15 11:25 UTC, darya-varabei commented
Mentioned issues have been improved recently

2022-01-03 12:21 UTC, EugeneItechart approved these changes
Could be merged

2022-01-04 09:08 UTC, merged